name: Build and Deploy to server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOYMENT_KEY }}

    - name: Build and deploy
      env:
        DEPLOYMENT_SERVER: ${{ secrets.DEPLOYMENT_SERVER }}
        DEPLOYMENT_USER: ${{ secrets.DEPLOYMENT_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $DEPLOYMENT_USER@$DEPLOYMENT_SERVER << 'EOF'
          cd htdocs/bloom/
          git pull origin develop
          sudo echo "REACT_APP_API_URL=${{ vars.DEV_API_URL }}" >> .env
          sudo echo "REACT_APP_ACCESS_AUTH_TOKEN=${{ vars.DEV_AUTH_API_TOKEN }}" >> .env
          cat .env
          npm install
          cd backend
          npm install
          pm2 restart all
        EOF